/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author gabri
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    JanelaRealizaVenda realizarVenda = new JanelaRealizaVenda();   
    JanelaManutencaoEstoque manutencaoEstoque = new JanelaManutencaoEstoque();   
    JanelaExibeVendas exibeVendas = new JanelaExibeVendas();   
    JanelaEstatisticas estatisticas = new JanelaEstatisticas();   
    
    public JanelaPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRaiz = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonVenda = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonVendas = new javax.swing.JButton();
        jButtonEstatisticas = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        jButtonControleEstoque = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jToolBar6 = new javax.swing.JToolBar();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButtonVenda.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconVendaCaixa_40px.png"))); // NOI18N
        jButtonVenda.setText("Venda");
        jButtonVenda.setFocusable(false);
        jButtonVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVenda.setMaximumSize(new java.awt.Dimension(70, 90));
        jButtonVenda.setMinimumSize(new java.awt.Dimension(70, 90));
        jButtonVenda.setPreferredSize(new java.awt.Dimension(70, 90));
        jButtonVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonVenda);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconOrcamento_40px.png"))); // NOI18N
        jButton2.setText("Orçamento");
        jButton2.setAutoscrolls(true);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(70, 90));
        jButton2.setMinimumSize(new java.awt.Dimension(70, 90));
        jButton2.setName(""); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(70, 90));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton3.setText("Consignação");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconDevolucao_40px.png"))); // NOI18N
        jButton4.setText("Devolução");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(70, 90));
        jButton4.setMinimumSize(new java.awt.Dimension(70, 90));
        jButton4.setPreferredSize(new java.awt.Dimension(70, 90));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton5.setText("Devolução");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator1);

        jButtonVendas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButtonVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconVendas_40px.png"))); // NOI18N
        jButtonVendas.setText("Vendas");
        jButtonVendas.setFocusable(false);
        jButtonVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVendas.setMaximumSize(new java.awt.Dimension(70, 90));
        jButtonVendas.setMinimumSize(new java.awt.Dimension(70, 90));
        jButtonVendas.setPreferredSize(new java.awt.Dimension(70, 90));
        jButtonVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonVendas);

        jButtonEstatisticas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButtonEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconEstatisticas_40px.png"))); // NOI18N
        jButtonEstatisticas.setText("Estatísticas");
        jButtonEstatisticas.setFocusable(false);
        jButtonEstatisticas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEstatisticas.setMaximumSize(new java.awt.Dimension(70, 90));
        jButtonEstatisticas.setMinimumSize(new java.awt.Dimension(70, 90));
        jButtonEstatisticas.setPreferredSize(new java.awt.Dimension(70, 90));
        jButtonEstatisticas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEstatisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEstatisticasMouseClicked(evt);
            }
        });
        jToolBar1.add(jButtonEstatisticas);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton8.setText("Movimentos");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton9.setText("Ultimo Cupom");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("Manutenção", jPanel1);

        jToolBar2.setRollover(true);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton10.setText("Venda");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton11.setText("Orçamento");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton12.setText("Consignação");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton12);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton13.setText("Devolução");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton14.setText("Devolução");
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton14);
        jToolBar2.add(jSeparator2);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton15.setText("Fechamento Caixa");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton16.setText("Transferência");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton16);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton17.setText("Movimentos");
        jButton17.setFocusable(false);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton17);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton18.setText("Ultimo Cupom");
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton18);

        jTabbedPane1.addTab("Consultas", jToolBar2);

        jToolBar3.setRollover(true);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton19.setText("Venda");
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton19);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton20.setText("Orçamento");
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton20);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton21.setText("Consignação");
        jButton21.setFocusable(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton21);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton22.setText("Devolução");
        jButton22.setFocusable(false);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton22);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton23.setText("Devolução");
        jButton23.setFocusable(false);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton23);
        jToolBar3.add(jSeparator3);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton24.setText("Fechamento Caixa");
        jButton24.setFocusable(false);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton24);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton25.setText("Transferência");
        jButton25.setFocusable(false);
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton25);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton26.setText("Movimentos");
        jButton26.setFocusable(false);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton26);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton27.setText("Ultimo Cupom");
        jButton27.setFocusable(false);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton27);

        jTabbedPane1.addTab("Impressão", jToolBar3);

        jToolBar4.setRollover(true);

        jButtonControleEstoque.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButtonControleEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconsContabilidade_40px.png"))); // NOI18N
        jButtonControleEstoque.setText("Controle de Estoque");
        jButtonControleEstoque.setToolTipText("");
        jButtonControleEstoque.setFocusable(false);
        jButtonControleEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonControleEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonControleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControleEstoqueActionPerformed(evt);
            }
        });
        jToolBar4.add(jButtonControleEstoque);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton30.setText("Consignação");
        jButton30.setFocusable(false);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton30);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton29.setText("Orçamento");
        jButton29.setFocusable(false);
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton29.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton29);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton31.setText("Devolução");
        jButton31.setFocusable(false);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton31);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton32.setText("Devolução");
        jButton32.setFocusable(false);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton32);
        jToolBar4.add(jSeparator4);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton33.setText("Fechamento Caixa");
        jButton33.setFocusable(false);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton33);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton34.setText("Transferência");
        jButton34.setFocusable(false);
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton34.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton34);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton35.setText("Movimentos");
        jButton35.setFocusable(false);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton35);

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton36.setText("Ultimo Cupom");
        jButton36.setFocusable(false);
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton36.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton36);

        jTabbedPane1.addTab("Cadastros e outras Operações", jToolBar4);

        jToolBar5.setRollover(true);

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton37.setText("Venda");
        jButton37.setFocusable(false);
        jButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton37.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton37);

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton38.setText("Orçamento");
        jButton38.setFocusable(false);
        jButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton38.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton38);

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton39.setText("Consignação");
        jButton39.setFocusable(false);
        jButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton39.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton39);

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton40.setText("Devolução");
        jButton40.setFocusable(false);
        jButton40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton40.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton40);

        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton41.setText("Devolução");
        jButton41.setFocusable(false);
        jButton41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton41.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton41);
        jToolBar5.add(jSeparator5);

        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton42.setText("Fechamento Caixa");
        jButton42.setFocusable(false);
        jButton42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton42.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton42);

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton43.setText("Transferência");
        jButton43.setFocusable(false);
        jButton43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton43.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton43);

        jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton44.setText("Movimentos");
        jButton44.setFocusable(false);
        jButton44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton44.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton44);

        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton45.setText("Ultimo Cupom");
        jButton45.setFocusable(false);
        jButton45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton45.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar5.add(jButton45);

        jTabbedPane1.addTab("Configurações", jToolBar5);

        jToolBar6.setRollover(true);

        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton46.setText("Venda");
        jButton46.setFocusable(false);
        jButton46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton46.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton46);

        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton47.setText("Orçamento");
        jButton47.setFocusable(false);
        jButton47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton47.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton47);

        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton48.setText("Consignação");
        jButton48.setFocusable(false);
        jButton48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton48.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton48);

        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton49.setText("Devolução");
        jButton49.setFocusable(false);
        jButton49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton49.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton49);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton50.setText("Devolução");
        jButton50.setFocusable(false);
        jButton50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton50.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton50);
        jToolBar6.add(jSeparator6);

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton51.setText("Fechamento Caixa");
        jButton51.setFocusable(false);
        jButton51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton51.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton51);

        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton52.setText("Transferência");
        jButton52.setFocusable(false);
        jButton52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton52.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton52);

        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton53.setText("Movimentos");
        jButton53.setFocusable(false);
        jButton53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton53.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton53);

        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus_30px_1.png"))); // NOI18N
        jButton54.setText("Ultimo Cupom");
        jButton54.setFocusable(false);
        jButton54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton54.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar6.add(jButton54);

        jTabbedPane1.addTab("Fiscal", jToolBar6);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("BALLOON");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_azul/iconBalloon_80px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRaizLayout = new javax.swing.GroupLayout(jPanelRaiz);
        jPanelRaiz.setLayout(jPanelRaizLayout);
        jPanelRaizLayout.setHorizontalGroup(
            jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRaizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );
        jPanelRaizLayout.setVerticalGroup(
            jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRaizLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRaizLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
         
        if(!(realizarVenda.isVisible())){
            realizarVenda = new JanelaRealizaVenda();
            realizarVenda.setVisible(true);
        }

    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jButtonControleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControleEstoqueActionPerformed
        
        if(!(manutencaoEstoque.isVisible())){
            manutencaoEstoque = new JanelaManutencaoEstoque();
            manutencaoEstoque.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonControleEstoqueActionPerformed

    private void jButtonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendasActionPerformed
        
        if(!(exibeVendas.isVisible())){
            exibeVendas = new JanelaExibeVendas();
            exibeVendas.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonVendasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonEstatisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEstatisticasMouseClicked
        if(!(estatisticas.isVisible())){
            estatisticas = new JanelaEstatisticas();
            estatisticas.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEstatisticasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonControleEstoque;
    private javax.swing.JButton jButtonEstatisticas;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JButton jButtonVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRaiz;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    // End of variables declaration//GEN-END:variables
}
